version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coniferbackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-115nnszaf6514"
s3_prefix = "coniferbackend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
